// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OohelpWebApps.Presentations.Domain;

#nullable disable

namespace OohelpWebApps.Presentations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220530150105_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OohelpWebApps.Presentations.Domain.Data.BoardDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Angle")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("DoorsDix")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IconColor")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("IconStyle")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("Lighting")
                        .HasColumnType("bit");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("Ots")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("OohelpWebApps.Presentations.Domain.Data.PoiDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IconColor")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("IconStyle")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId");

                    b.ToTable("Pois");
                });

            modelBuilder.Entity("OohelpWebApps.Presentations.Domain.Data.PresentationDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CardCode")
                        .HasColumnType("bit");

                    b.Property<bool>("CardMedia")
                        .HasColumnType("bit");

                    b.Property<bool>("CardPrice")
                        .HasColumnType("bit");

                    b.Property<bool>("CardSide")
                        .HasColumnType("bit");

                    b.Property<bool>("CardSupplier")
                        .HasColumnType("bit");

                    b.Property<bool>("CardType")
                        .HasColumnType("bit");

                    b.Property<bool>("ColumnCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("ColumnGrp")
                        .HasColumnType("bit");

                    b.Property<bool>("ColumnPrice")
                        .HasColumnType("bit");

                    b.Property<bool>("ColumnSupplier")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ShowOwner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("OohelpWebApps.Presentations.Domain.Data.BoardDto", b =>
                {
                    b.HasOne("OohelpWebApps.Presentations.Domain.Data.PresentationDto", "Presentation")
                        .WithMany("Boards")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("OohelpWebApps.Presentations.Domain.Data.PoiDto", b =>
                {
                    b.HasOne("OohelpWebApps.Presentations.Domain.Data.PresentationDto", "Presentation")
                        .WithMany("Pois")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("OohelpWebApps.Presentations.Domain.Data.PresentationDto", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Pois");
                });
#pragma warning restore 612, 618
        }
    }
}
